name: Build & Push Docker image

on:
  push:
    branches:
      - master
    paths:
      - 'APPVERSION'
  # Allow manual runs.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1.0.3

      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.1.0
        with:
          context: .
          file: ./Dockerfile
          tags: moncho/dry:latest
          platforms: linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64
          push: true
  
